### PR TITLE
Add LICENSE file

### LINKED ISSUE #1: LICENSE file
Hi,

Would it be possible to have a LICENSE file at the root for tasklogger?
Thanks a lot.

Bérénice

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

This PR should fix #1
I took the license mentioned in the `setup.py` file

Bérénice

### CODE REVIEW

**Comment by synapticarbors** [comment]
It would be good to add a `MANIFEST.in` file and include the license file there so that the license goes in the source distribution as required by GPL

https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template

**Comment by scottgigante** [comment]
Thanks both for your input! I don't know how I managed to leave off the license. I'll merge this PR and add a `MANIFEST.in` so it gets included in the distribution.

**Comment by bebatut** [comment]
😄 
Can you create a new release with the license? I am creating a conda recipe (via conda-forge: https://github.com/conda-forge/staged-recipes/pull/6800)

**Comment by synapticarbors** [comment]
I think it's ok to proceed with the conda-forge recipe with the license file manually included and then we can use the one from the source distribution once it's added in a future release, if that makes more sense in terms of `tasklogger`'s release schedule.

**Comment by scottgigante** [comment]
I'm happy to create a new release now 👍 Thanks for putting in the effort to get this on conda-forge! I'll also add a conda-forge badge to the readme 😄

**Pull request merged**
